language: python

dist: trusty

env:
  global:
    - CHANNELS=" -c conda-forge "
    - ANACONDA_UPLOAD_USER=elm
    - CHANNELS=" -c conda-forge"

  matrix:
    - PYTHON=3.6 NUMPY=1.12
#    - PYTHON=3.5 NUMPY=1.11
#    - PYTHON=2.7 NUMPY=1.11

install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda
    - conda install --name root conda-build

    - export ENV_NAME="$(echo xf_env_${PYTHON} | sed 's/\.//')"
    - conda remove --name $ENV_NAME || true
    - conda create $CHANNELS --name $ENV_NAME python=$PYTHON numpy=$NUMPY
    - source activate $ENV_NAME

script:
    # move to e.g. a docs stage before merging
    # - conda build -c conda-forge --python $PYTHON --numpy $NUMPY conda.recipe
    - pip install -e .
    # install nbsite (there's no conda package yet - hopefully coming soon)
    - conda install -c conda-forge sphinx beautifulsoup4 graphviz notebook jupyter ipykernel
    - pip install nbsite sphinx_ioam_theme
    - cd doc
    - nbsite_nbpagebuild.py ceball xarray_filters ../notebooks .
    - sphinx-build -b html . ./_build/html
    - nbsite_fix_links.py _build/html
    - nbsite_cleandisthtml.py ./_build/html take_a_chance
    - touch ./_build/html/.nojekyll
    - cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./doc/_build/html
  on:
    branch: website
